name: Docker Image CI

on:
  push:
    branches:    
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Github Packages
      run: docker login docker.pkg.github.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.GITHUB_BUILDER }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_BUILDER_TOKEN }}
    - name: Build all the things
      run: ./build.sh

