name: Docker Image CI

on:
  push:
    branches:    
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Github Packages
      run: docker login docker.pkg.github.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.GITHUB_BUILDER }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_BUILDER_TOKEN }}
    - name: Build the Docker image
      run: |
        . ./.env
        CONTAINER_REF=$(echo ${GITHUB_REF} | awk '{gsub(/^refs\/heads\/master$/, "latest"); n=split($0,a,"/"); print a[n]}')
        docker build . --file Dockerfile --tag docker.pkg.github.com/${GITHUB_REPOSITORY}/${CONTAINER_NAME}:${CONTAINER_REF}
    - name: Publish
      run: |
        . ./.env
        CONTAINER_REF=$(echo ${GITHUB_REF} | awk '{gsub(/^refs\/heads\/master$/, "latest"); n=split($0,a,"/"); print a[n]}')  
        docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/${CONTAINER_NAME}:${CONTAINER_REF}

