name: Docker Image CI

on:
  push:
    branches:    
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Github Packages
      run: docker login docker.pkg.github.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.GITHUB_BUILDER }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_BUILDER_TOKEN }}
    - name: Build Python 2.7.17
      run: make PYTHON_VERSION=2.7.17 ci
    - name: Build Python 3.8.1
      run: make PYTHON_VERSION=3.8.1 ci
    - name: AWSCLI v1.16.310
      run: make AWSCLI_VERSION=1.16.310 -C python_apps awscli
    - name: AWSCLI v2.0.0dev
      run: make AWSCLI_VERSION=2.0.0dev -C python_apps aws2cli
